base/blog/urls.py
from django.conf.urls import *
from base.blog.models import *
from base.blog.views import PostView, Main, ArchiveMonth


urlpatterns = patterns("blog.views",
    (r"^post/(?P<dpk>\d+)/$"		, PostView.as_view(), {}, "post"),
    (r"^archive_month/(\d+)/(\d+)/$"	, ArchiveMonth.as_view(), {}, "archive_month"),
    (r"^$"				, Main.as_view(), {}, "main"),
    # (r"^delete_comment/(\d+)/$"	, "delete_comment", {}, "delete_comment"),
)

base/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('base.views',
    url(r'^$', 'home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('blog.views',
    (r'^blog/', include('blog.urls'), "main"),
)

web_dja/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
admin.autodiscover()


def bad(request):
    """ Simulates a server error """
    1 / 0

urlpatterns = patterns('',
    (r'^blog/', include('base.blog.urls'), "main"),
    # Examples:
    # url(r'^$', 'web_dja.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bad/$', bad),
    url(r'', include('base.urls')),
)

base/blog/models.py
from django.db.models import *


notify = False

class Post(BaseModel):
    title = CharField(max_length=60)
    body = TextField()
    created = DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ["-created"]

    def __unicode__(self):
	return self.title


class Comment(BaseModel):
    author = CharField(max_length=60, blank=True)
    body = TextField()
    post = ForeignKey(Post, related_name="comments", blank=True, null=True)
    created = DateTimeField(auto_now_add=True)

    def __unicode__(self):
	return u"%s: %s" % (self.post, self.body[:60])

    def save(self, *args, **kwargs):
	"""Email when a comment is added."""
	if notify:
	    tpl = "Comment was added to '%s' by '%s': \n\n%s"
	    message = tp1 % (self.post, self.author, self.body)
	    from_addr = "no-reply@jeremyredd.com"
	    recipient_list = ["contact@jeremyredd.com"]

	    send_mail("New comment added", message, from_addr, recipient_list)
	super(Comment, self).save(*args, **kwargs)

base/blog/views.py
# Imports {{{
import time
from calendar import month_name

from blog.models import *

from mcbv.list_custom import DetailListCreateView
# }}}


class PostView(DetailListCreateView):
    """Show post, associated comments and an ``add comment'' form."""
    detail_model = Post
    list_model = Comment
    modelform_class = CommentForm
    related_name = "comments"
    fk_attr = "post"
    template_name = "blog/post.html"


class Main(ListView):
    list_model = Post
    paginate_by = 10
    template_name = "blog/list.html"

    def months(self):
	"""Make a list of months to show archive Links."""
	if not Post.obj.count(): return list()
	# set up variables
	current_year, current_month = time.localtime()[:2]
	first = Post.obj.order_by("created")[0]
	first_year = first.created.year
	first_month = first.created.month
	months = list()

	# Loop over years and months
	for year in range(current_year, first_year-1, -1):
	    start, end = 12, 0
	    if year == current_year : start = current_month
	    if year == first_year : end = first_month - 1

	for month in range(start, end, -1):
	    if Post.obj.filter(created__year=year, created__month=month):
		months.append((year, month, month_name[month]))
    return months


class CommentForm(ModelForm):

    class Meta:
	model = Comment
	exclude = ["post"]

    
    def clean_author(self):
    return self.cleaned_data.get("author") or "Anonymous"


class ArchiveMonth(Main):
    paginate_by = None

    def get_list_queryset(self):
	year, month = self.args
	return Post.obj.filter(created__year=year, created__month=month).order_by("created")




base/views.py
""" Views for the base application """

from django.shortcuts import render, render_to_response

from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse

from blog.models import Post, PostAdmin

def main(request):
    """Main Listing"""
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, 2)
    
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
	posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
	posts = paginator.page(paginator.num_pages)
	
    return render_to_response("base/list.html", dict(posts=posts, user=request.user))


def home(request):
    """ Default view for the root """
    return render(request, 'base/home.html')

base/templates/_layouts/base.html
{% load compress %}
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("Your Site") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% block meta %}
  {% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
  {% block cdn_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/css/bootstrap.min.css">
  {% endblock cdn_css %}

  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  {% block css %}{% endblock %}
  {% endcompress %}
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  {% compress js %}
  <script src="{% static 'js/libs/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
  {% endcompress %}
</head>
<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <header>
    {% block header %}{% endblock %}
  </header>

  <div role="main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    <div class="container">
      <hr>
      <p>&copy; Company 2013</p>
    </div>
    {% endblock footer %}
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  {% block cdn_js %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.9.1.min.js"><\/script>')</script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>
  {% endblock cdn_js %}

  <!-- scripts concatenated and minified via django-compressor -->
  {% compress js %}
  {% block js %}
  <script src="{% static 'js/main.js' %}"></script>
  {% endblock js %}
  {% endcompress %}
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
{% endblock %}
</body>
</html>

base/templates/base/home.html
{% extends "_layouts/base.html" %}

{% block css %}
{{block.super}}
<style>
/* Move down content because we have a fixed navbar that is 50px tall */
body {
  padding-top: 50px;
  padding-bottom: 20px;
}
</style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
<!-- This code is taken from http://getbootstrap.com/examples/jumbotron/ -->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more »</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
      </div>
    </div>

{% endblock %}

base/templates/blog/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head> <title>{% block title %}MyBlog{% endblock %}</title> </head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
                <h3>MyBlog</h3>
                {% if user.is_staff %}
                <a href="{% url admin:index %}">Admin</a>
                <a href="{% url admin:blog_post_add %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

base/templates/blog/list.html
<!-- SIDEBAR -->

{% block sidebar %}
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for ym in view.months %}
            {% ifchanged ym.0 %} {{ ym.0 }} <br /> {% endifchanged %}
            <a href="{% url 'archive_month' ym.0 ym.1 %}">{{ ym.2 }}</a> <br />
        {% endfor %}
        </p>
    </div>
{% endblock %}

<!-- LIST OF POSTS -->

{% block content %}
    <div class="main">
            {% for post in post_list %}
                <div class="title">{{ post.title }}</div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                    <div class="commentlink">
                        <a href="{% url 'post' post.pk %}">Comments ({{ post.comments.count }})</a>
                    </div>
                </ul>
            {% endfor %}

        {% include "paginator.html" %}
    </div>
{% endblock %}

base/templates/blog/post.html
{% block content %}
    <div class="main">

        <div class="title">{{ post.title }}</div>
        <ul>
            <div class="time">{{ post.created }}</div>
            <div class="body">{{ post.body|linebreaks }}</div>
        </ul>

        <hr />

        {% for comment in comment_list %}
            <ul>
                <div class="time">{{ comment.author }}</div>
                <div class="body">{{ comment.body|linebreaks }}</div>
            </ul>
        {% endfor %}


        <div id="reply">
        <form action="" method="POST"> {% csrf_token %}
            <table>
                {{ modelform.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        </div>
    </div>
{% endblock %}

base/templates/paginator.html
{% if object_list and paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}{{ extra_vars }}">prev &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ page_obj.number }} of {{ paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}{{ extra_vars }}"> &gt;&gt; next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}